/* SPDX-License-Identifier: GPL-2.0 */
/*
 * pon_mac_seq.h - PON MAC register init sequence
 *
 * Reverse-engineered from the stock Airoha xpon.ko (k5.4.55) shipped on
 * the Nokia Bell XG-040G-MD (Airoha AN7581 XGS-PON). Generated by
 * Tools/re_asm.py + Tools/batch_extract.py + Tools/gen_pon_seq.py.
 *
 * Every entry is a real register access captured at a set_xpon_data /
 * get_xpon_data call site. Offsets are relative to the PON MAC register
 * base 0x1fa80000 (an7581.dtsi pon_pcs block: GPON MAC @+0x4000.., EPON
 * MAC @+0x6000.., GEM/MIB @+0x41xx..). Replay with:
 *    PON_OP_W   -> writel(wval, base + off)
 *    PON_OP_RMW -> writel((readl(base+off) & and_mask) | or_val, base+off)
 *
 * NOTE: 'RMW?' entries (value not statically determinable) are excluded.
 * The optical link additionally requires the NPU XPON-HAL firmware
 * (airoha-en7581-npu-firmware) for serdes training + GTC/OMCI; these
 * register writes configure the MAC but do not by themselves bring
 * the laser up.
 */
#ifndef PON_MAC_SEQ_H
#define PON_MAC_SEQ_H

#include <linux/types.h>

enum pon_op_type { PON_OP_W = 0, PON_OP_RMW = 1 };

struct pon_reg_op {
    const char *tag;   /* originating function (for review) */
    u32 off;           /* register offset from PON MAC base */
    u32 type;          /* PON_OP_W | PON_OP_RMW */
    u32 wval;          /* PON_OP_W: value to write */
    u32 and_mask;      /* PON_OP_RMW: read mask */
    u32 or_val;        /* PON_OP_RMW: bits to set */
};

static const struct pon_reg_op pon_mac_seq[] = {
    /* gponDevSwReset: get REG[0x43a0] (read) */
    { "gponDevSwReset", 0x43a0, PON_OP_RMW, 0,          0xfffefffe, 0x00000000 },
    { "gponDevSwReset", 0x43a0, PON_OP_RMW, 0,          0xfffefffe, 0x00000001 },
    /* eponMacSwReset: get REG[0x6000] (read) */
    { "eponMacSwReset", 0x6000, PON_OP_RMW, 0,          0xffffffff, 0x00000010 },
    { "eponMacSwReset", 0x6000, PON_OP_RMW, 0,          0xffefffef, 0x00000000 },
    { "eponMacSwReset", 0x6100, PON_OP_RMW, 0,          0xffefffef, 0x00000000 },
    /* eponMacSwReset: get REG[0x6004] (read) */
    /* eponMacSwReset: get REG[0x602c] (read) */
    { "eponMacSwReset", 0x6000, PON_OP_RMW, 0,          0xffefffef, 0x00800042 },
    { "eponMacSwReset", 0x60d0, PON_OP_W,   0x202403e8, 0,          0 },
    { "eponMacSwReset", 0x6160, PON_OP_W,   0x382b0000, 0,          0 },
    { "gpon_dev_init", 0x43cc, PON_OP_W,   0x00000000, 0,          0 },
    { "eponStart", 0x623c, PON_OP_W,   0x00008000, 0,          0 },
    { "eponStart", 0x6160, PON_OP_W,   0x382b0010, 0,          0 },
    { "gponDevGemMibTablesInit", 0x4134, PON_OP_W,   0x00000001, 0,          0 },
    { "gponDevGemMibTablesInit", 0x4148, PON_OP_W,   0x00000001, 0,          0 },
    /* gponDevGemMibTablesInit: get REG[0x4134] (read) */
    /* gponDevGemMibTablesInit: get REG[0x4148] (read) */
    /* gponDevDeactiveOnu: get REG[0x4000] (read) */
    { "gponDevDeactiveOnu", 0x4000, PON_OP_RMW, 0,          0x7fff7fff, 0x00000000 },
    /* gponDevDeactiveOnu: get REG[0x4004] (read) */
    { "gponDevDeactiveOnu", 0x4004, PON_OP_RMW, 0,          0xfffefffe, 0x00000000 },
    { "gponDevResetAllocId", 0x4020, PON_OP_W,   0x00000000, 0,          0 },
    { "gponDevResetAllocId", 0x4024, PON_OP_W,   0x00000000, 0,          0 },
    { "gponDevResetAllocId", 0x4028, PON_OP_W,   0x00000000, 0,          0 },
    { "gponDevResetAllocId", 0x402c, PON_OP_W,   0x00000000, 0,          0 },
    { "gponDevResetAllocId", 0x4030, PON_OP_W,   0x00000000, 0,          0 },
    { "gponDevResetAllocId", 0x4034, PON_OP_W,   0x00000000, 0,          0 },
    { "gponDevResetAllocId", 0x4038, PON_OP_W,   0x00000000, 0,          0 },
    { "gponDevResetAllocId", 0x403c, PON_OP_W,   0x00000000, 0,          0 },
    { "gponDevResetGemInfo", 0x4040, PON_OP_W,   0x80000000, 0,          0 },
    /* gponDevResetGemInfo: get REG[0x4044] (read) */
    /* gpon_typeb_dev_reset_for_typeB: get REG[0x4160] (read) */
    { "gpon_typeb_dev_reset_for_typeB", 0x4160, PON_OP_RMW, 0,          0xffffffff, 0x00000010 },
    /* gpon_typeb_dev_reset_for_typeB: get REG[0x4160] (read) */
    { "gpon_typeb_dev_reset_for_typeB", 0x4160, PON_OP_RMW, 0,          0xffffffff, 0x00010000 },
    /* gpon_typeb_dev_reset_for_typeB: get REG[0x4160] (read) */
    /* gpon_typeb_dev_reset_for_typeB: get REG[0x4160] (read) */
    { "gpon_typeb_dev_reset_for_typeB", 0x4160, PON_OP_RMW, 0,          0xffffffff, 0x00000001 },
    /* gpon_typeb_dev_reset_for_typeB: get REG[0x4160] (read) */
    /* gpon_typeb_dev_reset_for_typeB: get REG[0x4160] (read) */
    { "gpon_typeb_dev_reset_for_typeB", 0x4160, PON_OP_RMW, 0,          0xffffffff, 0x00000100 },
    /* gpon_typeb_dev_reset_for_typeB: get REG[0x4160] (read) */
    /* gpon_typeb_dev_reset_for_typeB: get REG[0x4160] (read) */
    { "gpon_typeb_dev_reset_for_typeB", 0x4160, PON_OP_RMW, 0,          0xffffffff, 0x01000000 },
    /* gpon_typeb_dev_reset_for_typeB: get REG[0x4160] (read) */
    /* gpon_typeb_dev_reset_for_typeB: get REG[0x4160] (read) */
    { "gpon_typeb_dev_reset_for_typeB", 0x4160, PON_OP_RMW, 0,          0xfefffeff, 0x00000000 },
    /* gpon_typeb_dev_reset_for_typeB: get REG[0x4160] (read) */
    { "gpon_typeb_dev_reset_for_typeB", 0x4160, PON_OP_RMW, 0,          0xfefffeff, 0x00000000 },
    /* gpon_typeb_dev_reset_for_typeB: get REG[0x4160] (read) */
    { "gpon_typeb_dev_reset_for_typeB", 0x4160, PON_OP_RMW, 0,          0xfffefffe, 0x00000000 },
    /* gpon_typeb_dev_reset_for_typeB: get REG[0x4160] (read) */
    { "gpon_typeb_dev_reset_for_typeB", 0x4160, PON_OP_RMW, 0,          0xfffefffe, 0x00000000 },
    /* eponLlidEnable: get REG[0x6008] (read) */
    { "eponLlidEnable", 0x6008, PON_OP_RMW, 0,          0xffffffff, 0x00000000 },
    /* eponMacTxRxEnable: get REG[0x6000] (read) */
    { "eponMacTxRxEnable", 0x6000, PON_OP_RMW, 0,          0xfcfffcff, 0x00000000 },
    /* eponMacTxRxDisable: get REG[0x6000] (read) */
    { "eponMacTxRxDisable", 0x6000, PON_OP_RMW, 0,          0xffffffff, 0xffffffff },
};
#define PON_MAC_SEQ_N ARRAY_SIZE(pon_mac_seq)

#endif /* PON_MAC_SEQ_H */
