#!/bin/sh /etc/rc.common
# Quick config init script
# 启动时按 /etc/config/wuxuroute 的 auto_* 选项自动生成新 MAC / 主机名 / LAN IP

START=95

start() {
	/usr/sbin/wuxuroute boot
}

stop() {
	# 无后台进程，stop 不做事
	:
}

reload() {
	/usr/sbin/wuxuroute boot
}
